In [11]:
from sklearn.metrics import DistanceMetric
dist = DistanceMetric.get_metric('euclidean')   # Create a DistanceMetric object using the 'euclidean' metric
X = [[1, 2], [3, 4], [5, 6]]
Y = [[7, 8], [9, 10]]
dist.pairwise(X,Y) # Calculate the pairwise distances between points in X and Y using the euclidean metric

array([[ 8.48528137, 11.3137085 ],
       [ 5.65685425,  8.48528137],
       [ 2.82842712,  5.65685425]])

In [12]:
from sklearn.metrics import DistanceMetric
dist = DistanceMetric.get_metric('manhattan')   # Create a DistanceMetric object using the 'manhattan' metric
X = [[1, 2], [3, 4], [5, 6]]
Y = [[7, 8], [9, 10]]
dist.pairwise(X,Y)

array([[12., 16.],
       [ 8., 12.],
       [ 4.,  8.]])

In [13]:
from sklearn.metrics import DistanceMetric
dist=DistanceMetric.get_metric('chebyshev') #uses chebyshev form to calculate distance
X=[[1,2],[3,4],[5,6]]
Y=[[7,8],[9,10]]
dist.pairwise(X,Y)

array([[6., 8.],
       [4., 6.],
       [2., 4.]])

In [14]:
from sklearn.metrics import DistanceMetric
dist=DistanceMetric.get_metric('minkowski') #uses minkowski form to calculate
X=[[1,2],[3,4],[5,6]]
Y=[[7,8],[9,10]]
dist.pairwise(X,Y)

array([[ 8.48528137, 11.3137085 ],
       [ 5.65685425,  8.48528137],
       [ 2.82842712,  5.65685425]])

**Method 1:**

Load images (grayscale)

In [15]:
from PIL import Image
import numpy as np

img1 = Image.open("/content/OAS1_0028_MR1_mpr-1_100.jpg").convert("L")
img2 = Image.open("/content/OAS1_0028_MR1_mpr-1_101.jpg").convert("L")


Resize to a fixed size

In [16]:
SIZE = (128, 128)

img1 = img1.resize(SIZE)
img2 = img2.resize(SIZE)


Convert to NumPy arrays


In [17]:
arr1 = np.array(img1, dtype=np.float32)
arr2 = np.array(img2, dtype=np.float32)


Normalize pixel values


In [18]:
arr1 /= 255.0
arr2 /= 255.0


Flatten images into vectors


In [19]:
vec1 = arr1.flatten()
vec2 = arr2.flatten()


Euclidean Distance


In [20]:
euclidean = np.linalg.norm(vec1 - vec2)
print("Euclidean Distance:", euclidean)


Euclidean Distance: 5.7611065


Manhattan Distance

In [21]:
manhattan = np.sum(np.abs(vec1 - vec2))
print("Manhattan Distance:", manhattan)


Manhattan Distance: 394.9843


Chebyshev Distance


In [22]:
# Chebyshev Distance (L-infinity)
chebyshev = np.max(np.abs(vec1 - vec2))
print("Chebyshev Distance:", chebyshev)


Chebyshev Distance: 0.37254903


Minkowskii with p=1


In [23]:
# Minkowski Distance with p = 1
p = 1
minkowski_p1 = np.power(np.sum(np.abs(vec1 - vec2) ** p), 1 / p)
print("Minkowski Distance (p=1):", minkowski_p1)


Minkowski Distance (p=1): 394.9843


Minkowski Distance (p = 2) → Euclidean Distance


In [24]:
# Minkowski Distance with p = 2
p = 2
minkowski_p2 = np.power(np.sum(np.abs(vec1 - vec2) ** p), 1 / p)
print("Minkowski Distance (p=2):", minkowski_p2)


Minkowski Distance (p=2): 5.7611074


**Method 2:**

In [25]:
from skimage.io import imread
import numpy as np
i1=imread("/content/OAS1_0028_MR1_mpr-1_100.jpg",as_gray=True)
i2=imread("/content/OAS1_0028_MR1_mpr-1_101.jpg",as_gray=True)

v1= i1.flatten()
v2= i2.flatten()

dist1=DistanceMetric.get_metric('euclidean')
dist1.pairwise([v1],[v2])

array([[18.74790446]])

In [26]:
dist2=DistanceMetric.get_metric('manhattan')
dist2.pairwise([v1],[v2])

array([[3567.79607843]])

In [27]:
dist3=DistanceMetric.get_metric('chebyshev')
dist3.pairwise([v1],[v2])

array([[0.73333333]])

In [28]:
dist3=DistanceMetric.get_metric('minkowski')
dist3.pairwise([v1],[v2])

array([[18.74790446]])